spring:
  application:
  name: Service Builder

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  datasource:
    url: jdbc:postgresql://localhost:5432/vdt_query
    username: longlh20
    password: 123123aA@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  graphql:
    graphiql:
      enabled: true

server:
  port: 7554

app:
  kafka:
    topics:
      schema-parse: schema-parse-topic

camunda:
  client:
    mode: self-managed
    grpc-address: http://127.0.0.1:26500
    rest-address: http://127.0.0.1:8080

logging:
  level:
    io.camunda.client.impl.CamundaCallCredentials: ERROR
